spring:
  datasource:
    url: jdbc:h2:mem:mkobo
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
  flyway:
    locations: classpath:db/migration

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 5000


